
path: D:\WhereCodingStuff\pythonStuff\datasets\cat2 # dataset root dir
train: train  # train images (relative to 'path')
val: valid  # val images (relative to 'path')
test: test


# Classes
nc: 1
names: ['cat']